# Generated by Django 2.1.5 on 2019-01-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('request_time', models.DateTimeField(verbose_name='requested time')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='word_cloud.Website'),
        ),
    ]
