# Generated by Django 2.1.5 on 2019-01-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_cloud', '0002_auto_20190105_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='website',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
