# Generated by Django 2.1.5 on 2019-01-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cloud', '0003_auto_20190108_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.BinaryField(max_length=200),
        ),
    ]
